### ISSUE TITLE
Please do not use `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by peaceiris** [andykais/scrape-pages#38]
Check your GitHub Pages status, you find that GitHub Pages build event did not start.

- Please do not use `GITHUB_TOKEN`, use `ACTIONS_DEPLOY_KEY` or `PERSONAL_TOKEN` 
  - cf. https://github.com/peaceiris/actions-gh-pages/issues/9
- Please use the latest version of peaceiris/actions-gh-pages
  - [Releases · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/releases)

**Comment by andykais** [comment]
oh! Thank you for the PSA. I will fix this tonight

**Comment by andykais** [comment]
fixed in https://github.com/andykais/scrape-pages/commit/e19587cfec0b0c5a6de4a288df7a8b4e06832808 (though there was another problem with the build that was fixed in https://github.com/andykais/scrape-pages/commit/bbcf709268820094027412cf69e7df1c0be8d2e0)

**Comment by peaceiris** [comment]
LGTM. Thank you.
